# Generated by Django 5.1.7 on 2025-04-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='user', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
