# Generated by Django 5.1.7 on 2025-03-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='learninglog',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='resourcestatus',
            old_name='user',
            new_name='owner',
        ),
    ]
