# Generated by Django 5.1.7 on 2025-03-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_resource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcestatus',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
